language: go
sudo: true
go:
- "1.10"
script:
- echo "notest"
after_success:
- sudo apt-get update
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:ondrej/php -y
- sudo apt-get update
- sudo apt-get install php7.0
- bin/build-all.sh
- bin/generate_description.sh
deploy:
  provider: releases
  api_key:
    secure: fEKzU7ue9QFJDmiBwZcI5YVbl5NghAT6czxbYbVB2BcopdVbGfUbricEPcqwSibRrnSPUbQBbruNj2e1B71suPABhRlufi/o1MLryvT+Fcpk+u0eo3S8KbaG4jCS1iYM2BBgFDFmyDLTIn9/T9ijIP7o1LJqcWYs+M2EluQdGlidKDOQPxgKsGeNlcFe9uX3D+tPAElUQNd030MIQSEXrlBqFXVzL3h5z1EsUb4BSFfMwKjtePRAjpvmZ4TXm+K71RvHbTZQgo4uc7sBkP9s8zyk6qPEYF0eIE021lFbsOYM2H6GCtUrto52pHdfMaTttqJnw8OuyN62AtIMhhccrWZalnQfYQfcW718PymOAqCE4+GKN/CDMSVixwZhJhISi2zNUp1XOuWXoZ3bGIuHGwwwKI3j+WjXRdsPtllYGu/Twj/S/wFwbIn+fpMg9lM+WO2zwmRcP2SSalduy7C5oST4BqEFYb3D0M9JHkBNLfRjrw3NU4LReLdxl0Q8JlvihB3Gqm2l+n8OyCoVtiKMHvOfz6L1jvnIQN+47xAx3x7itUpSRPyGsNJVMvfm3A4D3vtjjBO4PIXRgd/s/8J0OsrcB8APvLl2e0eCxBl3u9ZpdpUr+zA0dHCvTSvSEOIM4lb31Oa5y2EkPuo83Sra4eJaQZSiw+bvenp9iVz9MeY=
  file:
  - out/cf-plugin-bg-restage_darwin_amd64
  - out/cf-plugin-bg-restage_linux_386
  - out/cf-plugin-bg-restage_linux_amd64
  - out/cf-plugin-bg-restage_windows_386.exe
  - out/cf-plugin-bg-restage_windows_amd64.exe
  - repo-index.yml
  skip_cleanup: true
  on:
    repo: orange-cloudfoundry/cf-plugin-bg-restage
    tags: true
